name: Royal Realty
favicon: null
layout_spectrum: 0.5506888928357512
typography_spectrum: 0.5194279905408621
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e0ebfd'
    - '#95969a'
    - '#608600'
    - '#5a3918'
  brandStrength: 0.5963054979220033
  lightness: 0.3021618355996907
  saturation: 0.43619675002992153
  rhythmicContrast: 0.5429037737194449
purpose: []
