name: Royal Realty
favicon: null
layout_spectrum: 0.5506888928357512
typography_spectrum: 0.5194279905408621
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#07374c'
    - '#1194c6'
    - '#d0d0d0'
    - '#7f7f7f'
  brandStrength: 0
  lightness: 1
  saturation: 0.43619675002992153
  rhythmicContrast: 0.5429037737194449
purpose: []
